name: ez_circle_avatar
description: A defensive, customizable avatar widget that automatically generates initials and colors from names.
version: 0.0.5
homepage: https://github.com/Evgenii-Zinner/ez_circle_avatar
repository: https://github.com/Evgenii-Zinner/ez_circle_avatar
issue_tracker: https://github.com/Evgenii-Zinner/ez_circle_avatar/issues
documentation: https://flutter.ezinner.com/ez_circle_avatar
topics:
  - flutter
  - ez flutter
  - avatar
  - ui
  - widgets
funding:
  - https://github.com/sponsors/Evgenii-Zinner/
  - https://thanks.dev/u/gh/evgenii-zinner
  - https://buymeacoffee.com/evgeniizinner

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
